apiVersion: v1
kind: Service
metadata:
  name: datii-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: datii
---
apiVersion: v1
kind: Service
metadata:
  name: datii-redis
spec:
  ports:
    - port: 6379
  selector:
    app: datii-redis
